# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbsstorytime',
                'doc_host': 'https://chrphb.github.io',
                'git_url': 'https://github.com/chrphb/nbsstorytime',
                'lib_path': 'nbsstorytime'},
  'syms': {'nbsstorytime.core': {'nbsstorytime.core.foo': ('core.html#foo', 'nbsstorytime/core.py')}}}
