"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['find_current_notebook', 'nbsstorytime_export']

# %% ../nbs/00_core.ipynb 9
import json
from ipykernel import get_connection_info
from fastcore.basics import Path

# %% ../nbs/00_core.ipynb 10
def find_current_notebook():
    conn_info = None
    try:
        conn_info = get_connection_info()
        if(not(conn_info)): return None
        conn_data = json.loads(conn_info)
        jupyter_session = conn_data.get('jupyter_session')
        if(jupyter_session):
            return Path(jupyter_session)
        else:
            return None
    except RuntimeError as e:
        print("not running in notebook", e)
        return None

# %% ../nbs/00_core.ipynb 11
from fastcore.basics import patch
import nbformat

@patch
def export_n4l_content(self:Path):
    """Add n4l export capability to any Path object"""
    # Load the notebook
    notebook = nbformat.read(self.open(), as_version=4)
    
    # Find n4l cells (your existing logic)
    n4l_contents = []
    for cell in notebook.cells:
        if (cell.cell_type == 'raw' and 
            cell.source.strip().startswith('#| n4l')):
            # Remove the marker line
            lines = cell.source.strip().split('\n')
            content = '\n'.join(lines[1:]).strip()
            n4l_contents.append(content)
    
    # Create output file
    output_path = self.with_suffix('.n4l')
    combined_content = '\n\n'.join(n4l_contents)
    output_path.write_text(combined_content)
    
    return output_path

# %% ../nbs/00_core.ipynb 13
def nbsstorytime_export():
    current_path = find_current_notebook()
    if(current_path): 
        current_path.export_n4l_content()
    else:
        print("no current notebook")
